language: rust

rust:
    - nightly

cache:
  directories:
    - /home/travis/.cargo

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  
script:
  - make build
  - make test
#  - cargo bench benches --lib --examples
